In [6]:
import numpy as np

In [7]:
arr_2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [8]:
arr_3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [9]:
# Subtration of arrays or the same shape causes the respective elements to carry out the operation
arr_3 - arr_2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [10]:
# Scalar addition this adds 5 to every element
arr_2 + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14,  6,  7,  8]])

In [11]:
# Scalar didvision causes each element to be divided by said scalar, same of mult.
arr_3 / 4

array([[2.75, 3.  , 3.25, 3.5 ],
       [3.75, 4.  , 4.25, 4.5 ],
       [4.75, 2.75, 3.  , 3.25]])

In [12]:
# Multiplication of two arrays of same shape
arr_2 * arr_3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [13]:
# Modulus using a scalar return the remainder obtained by each element after a division by the figure
arr_2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)