In [2]:
import numpy as np

In [4]:
Practice_1 = np.array([
    [[1,2,3,4],
     [5,6,7,8]],
    
    [[9,10,11,12],
      [13,14,15,16]],
    
    [[17,18,19,20],
     [21,22,23,24]]
    ])

In [5]:
Practice_1.shape

(3, 2, 4)

In [14]:
#This is me slicing to get element 15 out of the array, to me it behaves much like list slicing with a twist.
Practice_1[1,1,2]

15

In [17]:
#Array slicing using ranges, let's say for instance I want to print from  [5,6]
Practice_1[0:1, 1:, :2]



array([[[13, 14, 15]],

       [[21, 22, 23]]])

In [22]:
#so to get 13-21
Practice_1[1:, 1:2,   0:1 ]

array([[[13]],

       [[21]]])

In [24]:
#So mixing ranges and indices
Practice_1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [25]:
Practice_1[0:2, 1, 3]

array([ 8, 16])

In [26]:
#For 11 and 19
Practice_1[1:, 0,2]

array([11, 19])