In [1]:
import numpy as np

In [5]:
#Creating a null matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#Creating a ones matrix
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# All ones
np.ones([2, 2, 3]) #Notice this looks like a list not tuple like previous , you can do it both ways

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
# To create the identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#Random matrix
np.random.randn(2,3)

array([[ 0.75137676,  0.33369606,  0.86474862],
       [ 0.64915827, -0.04240068, -0.41263741]])

In [17]:
#Giving a range
np.arange(10,85,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [22]:
np.arange(10,85,5).reshape(5,3)

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80]])

In [14]:
#creating a matrix of one element
np.full([3,4],24)

array([[24, 24, 24, 24],
       [24, 24, 24, 24],
       [24, 24, 24, 24]])

In [15]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])