In [4]:
Accra_temp = 34
Accra_rainfall = 79
Accra_humidity = 43

In [5]:
w1, w2, w3 = 0.3, 0.2, 0.5 #weighted averages....
kanto_yield_apples = Accra_temp * w1 + Accra_rainfall * w2 + Accra_humidity *43
print(kanto_yield_apples)
print("The expected yeild of apples in the Kanto regionn is {}".format(kanto_yield_apples))

1875.0
The expected yeild of apples in the Kanto regionn is 1875.0


In [16]:
Accra = [73, 67, 43]
Kumasi = [91, 88, 64]
Aburi = [28,74,36]

weights = [w1, w2, w3]

def expected_yield(region,weights):
    result = 0
    for i,x in zip(region, weights):
        result += i * x
    return result

expected_yield(Accra, weights)


56.8

In [11]:
expected_yield(Kumasi, weights )

76.9

In [5]:
Osu = [1,2,3]
Late = [4,5,6]
Kumawu = [7,8,9]

weights = [1,2,3]


def yield_1(region, weights):
    res = 0
    for i,y in zip(region, weights):
        res += i * y
    return res

yield_1(Osu,weights)

14

In [1]:
!pip install numpy 

In [4]:
#Learning how to use numpy from zeros to pandas course
import numpy as np
Accra = np.array([73, 67, 43])

weights = np.array([0.3, 0.2, 0.5])

x = (Accra * weights)
print(x)

expected_yield_Accra = np.dot(Accra, weights)
print('The expected yield in Accra is', expected_yield_Accra)

[21.9 13.4 21.5]
The expected yield in Accra is 56.8


In [12]:
#code to test time it takes to perform dot multiplication of vectors without numpy


notyet_arr_1 = list(range(1000000))
notyet_arr_2 = list(range(1000000,2000000))

dot_m = 0
for i,x in zip(notyet_arr_1, notyet_arr_2):
    dot_m += (i * x)
    
print(dot_m)

    

833332333333500000


In [14]:

#Figure out why this ans is wrong
import numpy as np
arr_1 = np.array(notyet_arr_1)
arr_2 = np.array(notyet_arr_2)
dot_m_2 = np.dot(arr_1, arr_2)
print(dot_m_2)



-1942957984


In [9]:
import numpy as np
arr_n_1 = np.array([1,2,3])
arr_n_2 = np.array([1,2,3])

dot_p = np.dot(arr_n_1,arr_n_2)
print(dot_p)

14


In [18]:
#This is a 1-D matrix
x_1 = np.array([1,2,3])
x_1.shape

(3,)

In [21]:
#This is a 2-D matrix
x_2 =np.array([[1,2,3],
               [4,5,6],
              [7,8,9],
              [4,5,6]])
x_2.shape

(4, 3)

In [27]:
#This is a 3-D matrix
x_3 = np.array( [ [[1,2],[3,4]],
       [[3,4], [3,4]], 
       [[5,6], [5,6]],
       [[7,8], [7,8]] ] )
x_3.shape

(4, 2, 2)

All the elements in a numpy array have the same data type. You can check the data type of an array using the .dtype property

In [31]:
 # Here you will input the temp, rainfall , humidity of each region in order
climate_data = np.array([[1,2,3],
               [4,5,6],
              [7,8,9],
              [4,5,6]])

weights = np.array([0.3, 0.4, 0.5])

#So instead of defining a function we can use matmul to perform a matrix multiplication at once. It will give us the dot product of each region
expected_yield_per_region = np.matmul(climate_data, weights)
print(expected_yield_per_region)

#So if first details were of Kumasi the first figure is expected yield n Kumasi(dot product already done)

print(climate_data @ weights) # shortcut to matmult

[2.6 6.2 9.8 6.2]
[2.6 6.2 9.8 6.2]
